wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 8
DATASET:
  desc: null
  value: image_data
EPOCHS:
  desc: null
  value: 100
HEIGHT:
  desc: null
  value: 128
LR:
  desc: null
  value: 0.0002
WIDTH:
  desc: null
  value: 204
_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1657832060
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 13
      - 16
      4: 3.9.13
      5: 0.12.21
      8:
      - 3
      - 5
